version: '3'

services:
  tooljet_server:
    tty: true
    stdin_open: true
    image: ${FIRST_BASE_IMAGE}
    restart: unless-stopped
    container_name: ${STACK_NAME:-defstack}_tooljet
    env_file: .env
    ports:
      - 8083:${TOOLJET_SERVER_PORT}
    environment:
      - SERVE_CLIENT=true
      - PORT=${TOOLJET_SERVER_PORT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tooljet_server.rule=Host(`tooljet.${DOMAIN_NAME}`)"
      - "traefik.http.services.tooljet_server.loadbalancer.server.port=${TOOLJET_SERVER_PORT}"
    command: npm run start:prod
    depends_on:
      - postgresdb
    networks:
     - mydefaultstack

networks:
  mydefaultstack:
    name: mydefaultstack
    external: true
